general_ml:
  seed: 123
  encoding: iso-8859-1
  cloud: AWS

paths:
  project_dir: ...
  raw_data: ${hydra:runtime.cwd}/data/raw
  interim_data: ${hydra:runtime.cwd}/data/interim
  processed_data: ${hydra:runtime.cwd}/data/processed
  reports: ${hydra:runtime.cwd}/reports

cloud_paths:
  bucket_path: !|
    dif-!{cookiecutter.client}-!{cookiecutter.project}-bucket
  
  mlflow-path: >
      ${bucket_path}/mlflow/bucket
  
  reports_path: >
      dif-{{cookiecutter.client.lower().replace(' ', '_')}}-
      {{cookiecutter.project.lower().replace(' ', '_')}}-
      bucket/{{ cookiecutter.experiment.lower().replace(' ', '_')}}
      /reports
  rawdata_path: >
      dif-{{cookiecutter.client.lower().replace(' ', '_')}}-
      {{cookiecutter.project.lower().replace(' ', '_')}}-
      bucket/{{ cookiecutter.experiment.lower().replace(' ', '_')}}
      /raw-data
  dvc_path: >
      dif-{{cookiecutter.client.lower().replace(' ', '_')}}-
      {{cookiecutter.project.lower().replace(' ', '_')}}-
      bucket/{{ cookiecutter.experiment.lower().replace(' ', '_')}}
      /dvc-store

file_names:
  raw_file : raw_file.csv
  data_file: datafile.csv
  train_features: train_features.csv
  train_labels: train_labels.csv
  validation_features: valid_features.csv
  validation_labels: valid_labels.csv
  test_features: test_features.csv
  test_labels: test_labels.csv
  data_profiling_report: data_profiling_report

data_fields:
  description: About what is the dataset
  label: match
  
  

data_pipeline:

  drop_features: ['field', 'from','zipcode','undergra','race','race_o']
  keep_features: ['dec_o', 'dec', 'like', 'attr', 'from', 'zipcode', 'prob', 
                  'like_o', 'fun', 'undergra', 'match']
  standarize_text: ['field','from','zipcode','undergra']
  str_to_float: ['income']
  to_categorize: ['field', 'from','zipcode','undergra','race','race_o']
  category_to_num: ['field','from','zipcode','undergra']
  onehot_encoding: ['race','race_o']

  #-----------------------------------------------
  # categorical variables to transform to numerical variables
  numerical_vars_from_numerical: ['income', 'mn_sat', 'tuition']

  # categorical variables to encode
  categorical_vars: ['undergra', 'zipcode']
  categorical_label_extraction: ['zipcode']
  
  # specify the ml algo
  pipeline01: decisiontree
  #--------------------------------

  data_transform_params:
    percent_valid: 0.20
    percent_test: 0.10

mlflow:
  tracking_uri: 0.0.0.0:5000
  tracking_experiment_name: Match4


  